# Generated by Django 5.2.15 on 2026-06-24 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoPrueba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Grupo de prueba',
                'verbose_name_plural': 'Grupos de prueba',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='MarcaVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Marca de vehículo',
                'verbose_name_plural': 'Marcas de vehículos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Aspecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=80, unique=True)),
                ('nombre', models.CharField(max_length=250)),
                ('unidad_medida', models.CharField(blank=True, max_length=50, null=True)),
                ('tipo_evaluacion', models.CharField(choices=[('MINIMO', 'Mínimo permitido'), ('MAXIMO', 'Máximo permitido'), ('RANGO', 'Rango permitido'), ('REFERENCIAL', 'Referencial')], default='REFERENCIAL', max_length=20)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('grupo_prueba', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aspectos', to='core.grupoprueba')),
            ],
            options={
                'verbose_name': 'Aspecto técnico',
                'verbose_name_plural': 'Aspectos técnicos',
                'ordering': ['grupo_prueba__nombre', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='LineaVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('activo', models.BooleanField(default=True)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='core.marcavehiculo')),
            ],
            options={
                'verbose_name': 'Línea de vehículo',
                'verbose_name_plural': 'Líneas de vehículos',
                'ordering': ['marca__nombre', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoPruebaVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(db_index=True, max_length=20)),
                ('modelo', models.IntegerField(blank=True, null=True)),
                ('tipo_servicio', models.CharField(blank=True, max_length=120, null=True)),
                ('tipo_combustible', models.CharField(blank=True, max_length=120, null=True)),
                ('tipo_linea', models.CharField(blank=True, max_length=120, null=True)),
                ('valor_medido', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('valor_norma', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('resultado', models.CharField(blank=True, max_length=80, null=True)),
                ('fecha_prueba', models.DateTimeField(blank=True, null=True)),
                ('datos_originales', models.JSONField(blank=True, null=True)),
                ('fecha_cargue', models.DateTimeField(auto_now_add=True)),
                ('aspecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.aspecto')),
                ('grupo_prueba', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.grupoprueba')),
                ('linea', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.lineavehiculo')),
                ('marca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.marcavehiculo')),
            ],
            options={
                'verbose_name': 'Histórico de prueba de vehículo',
                'verbose_name_plural': 'Histórico de pruebas de vehículos',
                'ordering': ['-fecha_prueba'],
            },
        ),
        migrations.CreateModel(
            name='NormativaAspecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_norma', models.CharField(max_length=200)),
                ('version', models.CharField(blank=True, max_length=100, null=True)),
                ('valor_minimo', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('valor_maximo', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('valor_objetivo', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('aplica_desde_modelo', models.IntegerField(blank=True, null=True)),
                ('aplica_hasta_modelo', models.IntegerField(blank=True, null=True)),
                ('tipo_servicio', models.CharField(blank=True, max_length=120, null=True)),
                ('tipo_combustible', models.CharField(blank=True, max_length=120, null=True)),
                ('tipo_linea', models.CharField(blank=True, max_length=120, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('aspecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='normativas', to='core.aspecto')),
            ],
            options={
                'verbose_name': 'Normativa por aspecto',
                'verbose_name_plural': 'Normativas por aspecto',
                'ordering': ['aspecto__codigo', 'nombre_norma'],
            },
        ),
        migrations.AddConstraint(
            model_name='lineavehiculo',
            constraint=models.UniqueConstraint(fields=('marca', 'nombre'), name='unique_linea_por_marca'),
        ),
        migrations.AddIndex(
            model_name='historicopruebavehiculo',
            index=models.Index(fields=['placa'], name='core_histor_placa_5ff0b7_idx'),
        ),
        migrations.AddIndex(
            model_name='historicopruebavehiculo',
            index=models.Index(fields=['modelo'], name='core_histor_modelo_224bbc_idx'),
        ),
        migrations.AddIndex(
            model_name='historicopruebavehiculo',
            index=models.Index(fields=['resultado'], name='core_histor_resulta_afc2e2_idx'),
        ),
        migrations.AddIndex(
            model_name='historicopruebavehiculo',
            index=models.Index(fields=['fecha_prueba'], name='core_histor_fecha_p_e1f987_idx'),
        ),
    ]
